const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const INTERNAL_ERROR = 500;
const RESPONSE_OK = 200;
const RESPONSE_OK_CREATED = 201;
const RESPONSE_OK_CONFIRMED = 201;
const RESPONSE_OK_NO_CONTENT = 204;
const RESPONSE_REDIRECTION_NO_MODIFIED = 304;
const DUPLICATE_KEY_ERROR = 11000;

const REQUEST_TIMEOUT = 408;

module.exports = {
  NOT_FOUND_ERROR,
  BAD_REQUEST_ERROR,
  INTERNAL_ERROR,
  RESPONSE_OK,
  RESPONSE_OK_NO_CONTENT,
  RESPONSE_REDIRECTION_NO_MODIFIED,
  RESPONSE_OK_CREATED,
  RESPONSE_OK_CONFIRMED,
  DUPLICATE_KEY_ERROR,
  REQUEST_TIMEOUT

};
